package com.mycompany.smarteduapp;

import java.util.*;
import java.awt.Color;
import java.io.File;
import java.sql.*;
import javax.swing.JRadioButton;

/**
 *
 * @author ethan
 */
public class AddClassScreen extends javax.swing.JFrame {
    HashMap<String,JRadioButton> dayButton;
    HashMap<String,GraphicsPanel> dayPanel;
    HashMap<String,Integer> dayInt;

    /**
     * Creates new form AddClassScreen
     */
    public AddClassScreen() {
        initComponents();
        
        dayButton = new HashMap();
        dayButton.put("MON",this.monRadioButton);
        dayButton.put("TUE",this.tueRadioButton);
        dayButton.put("WED",this.wedRadioButton);
        dayButton.put("THU",this.thuRadioButton);
        dayButton.put("FRI",this.friRadioButton);
        dayButton.put("SAT",this.satRadioButton);
        dayButton.put("SUN",this.sunRadioButton);
        
        dayPanel = new HashMap();
        dayPanel.put("MON",SmartEDUApp.main.gPanMon);
        dayPanel.put("TUE",SmartEDUApp.main.gPanTue);
        dayPanel.put("WED",SmartEDUApp.main.gPanWed);
        dayPanel.put("THU",SmartEDUApp.main.gPanThu);
        dayPanel.put("FRI",SmartEDUApp.main.gPanFri);
        dayPanel.put("SAT",SmartEDUApp.main.gPanSat);
        dayPanel.put("SUN",SmartEDUApp.main.gPanSun);
        
        dayInt = new HashMap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thurRadioButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        courseTitleField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        endTimeField = new javax.swing.JTextField();
        startTimeField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        monRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        tueRadioButton = new javax.swing.JRadioButton();
        wedRadioButton = new javax.swing.JRadioButton();
        thuRadioButton = new javax.swing.JRadioButton();
        friRadioButton = new javax.swing.JRadioButton();
        satRadioButton = new javax.swing.JRadioButton();
        sunRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        thurRadioButton.setBackground(new java.awt.Color(241, 196, 15));
        thurRadioButton.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Course");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course Title");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Location");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Start Time");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("End Time");

        endTimeField.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        endTimeField.setText("HH:MM");

        startTimeField.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        startTimeField.setText("HH:MM");

        confirmButton.setBackground(new java.awt.Color(34, 116, 165));
        confirmButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(34, 116, 165));
        cancelButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        monRadioButton.setBackground(new java.awt.Color(241, 196, 15));
        monRadioButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        monRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        monRadioButton.setText("Monday");

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Days");

        tueRadioButton.setBackground(new java.awt.Color(241, 196, 15));
        tueRadioButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        tueRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tueRadioButton.setText("Tuesday");
        tueRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tueRadioButtonActionPerformed(evt);
            }
        });

        wedRadioButton.setBackground(new java.awt.Color(241, 196, 15));
        wedRadioButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        wedRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        wedRadioButton.setText("Wednesday");

        thuRadioButton.setBackground(new java.awt.Color(241, 196, 15));
        thuRadioButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        thuRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        thuRadioButton.setText("Thursday");
        thuRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thuRadioButtonActionPerformed(evt);
            }
        });

        friRadioButton.setBackground(new java.awt.Color(241, 196, 15));
        friRadioButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        friRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        friRadioButton.setText("Friday");

        satRadioButton.setBackground(new java.awt.Color(241, 196, 15));
        satRadioButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        satRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        satRadioButton.setText("Saturday");
        satRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satRadioButtonActionPerformed(evt);
            }
        });

        sunRadioButton.setBackground(new java.awt.Color(241, 196, 15));
        sunRadioButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        sunRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        sunRadioButton.setText("Sunday");

        javax.swing.GroupLayout thurRadioButtonLayout = new javax.swing.GroupLayout(thurRadioButton);
        thurRadioButton.setLayout(thurRadioButtonLayout);
        thurRadioButtonLayout.setHorizontalGroup(
            thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thurRadioButtonLayout.createSequentialGroup()
                .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thurRadioButtonLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(thurRadioButtonLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(thurRadioButtonLayout.createSequentialGroup()
                                .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monRadioButton)
                                    .addComponent(tueRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wedRadioButton)
                                    .addComponent(thuRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(thurRadioButtonLayout.createSequentialGroup()
                                        .addComponent(friRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sunRadioButton))
                                    .addComponent(satRadioButton)))
                            .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(endTimeField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(startTimeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(courseTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(thurRadioButtonLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        thurRadioButtonLayout.setVerticalGroup(
            thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thurRadioButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(courseTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(thurRadioButtonLayout.createSequentialGroup()
                        .addComponent(monRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tueRadioButton))
                    .addGroup(thurRadioButtonLayout.createSequentialGroup()
                        .addComponent(wedRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thuRadioButton))
                    .addGroup(thurRadioButtonLayout.createSequentialGroup()
                        .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(friRadioButton)
                            .addComponent(sunRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(satRadioButton))
                    .addGroup(thurRadioButtonLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thurRadioButtonLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thurRadioButtonLayout.createSequentialGroup()
                        .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(endTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGroup(thurRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thurRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thurRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Confirm button pressed.
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        this.setVisible(false);
        
        // Ints used to save if the class meets on a certain day in the DB.  1 is true, 0 is false in SQL.
        /*int monClass,tueClass,wedClass,thuClass,friClass,satClass,sunClass;
        monClass = 0;
        tueClass = 0;
        wedClass = 0;
        thuClass = 0;
        friClass = 0;
        satClass = 0;
        sunClass = 0;*/
        
        // Get user inputs.
        String courseText = this.courseTitleField.getText();
        String locText = this.locationField.getText();
        String startTime = this.startTimeField.getText();
        String endTime = this.endTimeField.getText();
        
        // Generate a random color for this class.
        Random rand = new Random();
        int rVal = rand.nextInt(30,255);
        int gVal = rand.nextInt(30,255);
        int bVal = rand.nextInt(30,255);
        Color courseColor = new Color(rVal,gVal,bVal);
        
        // Create a new CourseBlock instance to represent this class.
        CourseBlock newCourse = new CourseBlock(courseText,locText,startTime,endTime,courseColor);
        
        // Boolean tracks if course was successfully added to a panel.
        boolean courseAdded = false;
        
        
        // Trys to add to panel.
        for (String day : dayButton.keySet()) {
            JRadioButton currButton = dayButton.get(day);
            GraphicsPanel currPanel = dayPanel.get(day);
            if (currButton.isSelected() && !currPanel.conflictExists(newCourse)) {
                currPanel.addCourse(newCourse,courseText);
                currPanel.repaint();
                dayInt.put(day,1);
                if (!courseAdded) {
                    courseAdded = true;
                }
            }
        }
        
        /*
        // Trys to add to monday panel.
        if (this.monRadioButton.isSelected() && !SmartEDUApp.main.gPanMon.conflictExists(newCourse)) {
            SmartEDUApp.main.gPanMon.addCourse(newCourse,courseText);
            SmartEDUApp.main.gPanMon.repaint();
            monClass = 1;
            if (!courseAdded) {
                courseAdded = true;
            }
        }
        // Trys to add to tuesday panel.
        if (this.tueRadioButton.isSelected() && !SmartEDUApp.main.gPanTue.conflictExists(newCourse)) {
            SmartEDUApp.main.gPanTue.addCourse(newCourse,courseText);
            SmartEDUApp.main.gPanTue.repaint();
            tueClass = 1;
            if (!courseAdded) {
                courseAdded = true;
            }
        }
        // Trys to add to wednesday panel.
        if (this.wedRadioButton.isSelected() && !SmartEDUApp.main.gPanWed.conflictExists(newCourse)) {
            SmartEDUApp.main.gPanWed.addCourse(newCourse,courseText);
            SmartEDUApp.main.gPanWed.repaint();
            wedClass = 1;
            if (!courseAdded) {
                courseAdded = true;
            }
        }
        // Trys to add to thursday panel.
        if (this.thuRadioButton.isSelected() && !SmartEDUApp.main.gPanThu.conflictExists(newCourse)) {
            SmartEDUApp.main.gPanThu.addCourse(newCourse,courseText);
            SmartEDUApp.main.gPanThu.repaint();
            thuClass = 1;
            if (!courseAdded) {
                courseAdded = true;
            }
        } 
        // Trys to add to friday panel.
        if (this.friRadioButton.isSelected() && !SmartEDUApp.main.gPanFri.conflictExists(newCourse)) {
            SmartEDUApp.main.gPanFri.addCourse(newCourse,courseText);
            SmartEDUApp.main.gPanFri.repaint();
            friClass = 1;
            if (!courseAdded) {
                courseAdded = true;
            }
        }
        // Trys to add to saturday panel.
        if (this.satRadioButton.isSelected() && !SmartEDUApp.main.gPanSat.conflictExists(newCourse)) {
            SmartEDUApp.main.gPanSat.addCourse(newCourse,courseText);
            SmartEDUApp.main.gPanSat.repaint();
            satClass = 1;
            if (!courseAdded) {
                courseAdded = true;
            }
        }
        // Trys to add to sunday panel.
        if (this.sunRadioButton.isSelected() && !SmartEDUApp.main.gPanSun.conflictExists(newCourse)) {
            SmartEDUApp.main.gPanSun.addCourse(newCourse,courseText);
            SmartEDUApp.main.gPanSun.repaint();
            sunClass = 1;
            if (!courseAdded) {
                courseAdded = true;
            }
        }
        */
        
        // Save to DB.
        if (courseAdded) {
            Connection conn = null;
            Statement state = null;
            try {
                String url = "jdbc:mariadb://localhost:3307/academicdb";
                conn = DriverManager.getConnection(url,"root","");
                
                int monClass,tueClass,wedClass,thuClass,friClass,satClass,sunClass;
                monClass = dayInt.get("MON");
                tueClass = dayInt.get("TUE");
                wedClass = dayInt.get("WED");
                thuClass = dayInt.get("THU");
                friClass = dayInt.get("FRI");
                satClass = dayInt.get("SAT");
                sunClass = dayInt.get("SUN");

                String insertQuery = "insert into schedule values ('"+courseText+"','"+locText+"',"+monClass+","+tueClass+","+wedClass+","+thuClass+","+friClass+","+satClass+","+sunClass+",'"+startTime+"','"+endTime+"',"+rVal+","+gVal+","+bVal+")";

                state = conn.createStatement();
                state.executeQuery(insertQuery);
            } catch (Exception e) {
                System.out.println(e.toString());
            } finally {
                if (state != null) try { state.close(); } catch (Exception e2) {}
                if (conn != null) try { conn.close(); } catch (Exception e3) {}
            }
        }
        
        // Create a course directory.
        try {
            File file = new File(".\\smartEDUFiles\\"+courseText);
            if (!file.exists()) {
                if (file.mkdir()) {
                    System.out.println("Class directory created.");
                } else {
                    System.out.println("Class directory creation failure.");
                }
            } else {
                System.out.println("Class directory ALREADY exists.");
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        
        // Reset fields.
        courseTitleField.setText("");
        endTimeField.setText("");
        locationField.setText("");
        startTimeField.setText("HH:MM");
        endTimeField.setText("HH:MM");
        // ADD HANDLING TO RESET RADIO BUTTONS HERE LATER. - TODO!
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Reset fields.
        courseTitleField.setText("");
        endTimeField.setText("");
        locationField.setText("");
        startTimeField.setText("HH:MM");
        endTimeField.setText("HH:MM");
        // ADD HANDLING TO RESET RADIO BUTTONS HERE LATER. - TODO!
        
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void tueRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tueRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tueRadioButtonActionPerformed

    private void thuRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thuRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thuRadioButtonActionPerformed

    private void satRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClassScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField courseTitleField;
    private javax.swing.JTextField endTimeField;
    private javax.swing.JRadioButton friRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField locationField;
    private javax.swing.JRadioButton monRadioButton;
    private javax.swing.JRadioButton satRadioButton;
    private javax.swing.JTextField startTimeField;
    private javax.swing.JRadioButton sunRadioButton;
    private javax.swing.JRadioButton thuRadioButton;
    private javax.swing.JPanel thurRadioButton;
    private javax.swing.JRadioButton tueRadioButton;
    private javax.swing.JRadioButton wedRadioButton;
    // End of variables declaration//GEN-END:variables
}
