/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.smarteduapp;
import javax.swing.JFrame;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;

/**
 *
 * @author ethan
 */
public class AssignmentScreen extends javax.swing.JFrame {
    HashMap<String,CourseTable> tables;
    /**
     * Creates new form MainScreen
     */
    public AssignmentScreen() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        tables = new HashMap();
        
        //assignPanel.setLayout(new BoxLayout(assignPanel,BoxLayout.Y_AXIS));
        assignPanel.setLayout(new GridLayout(10,0));
        
        // Testing
        // Load from DB.
        Connection conn = null;
        Statement state = null;
        ResultSet rs = null;
        
        try {
            String url = "jdbc:mariadb://localhost:3307/academicdb";
            conn = DriverManager.getConnection(url,"root","");
            
            String queryCourses = "select courseTitle,rVal,gVal,bVal from schedule";
           
            state = conn.createStatement();
            rs = state.executeQuery(queryCourses);
            
            while (rs.next()) {
                String courseTitle = rs.getString("courseTitle");
                int rVal = rs.getInt("rVal");
                int gVal = rs.getInt("gVal");
                int bVal = rs.getInt("bVal");
                Color courseColor = new Color(rVal,gVal,bVal);
                
                CourseTable newTable = new CourseTable(courseTitle,courseColor);
                tables.put(courseTitle,newTable);
                assignPanel.add(newTable);
            }
        } catch (Exception e) {
            
        } finally {
            if (rs != null) try { rs.close(); } catch (Exception e2) {}
            if (state != null) try { state.close(); } catch (Exception e3) {}
            if (conn != null) try { conn.close(); } catch (Exception e4) {}
        }
        
        CourseTable otherTable = new CourseTable("Other",Color.black);
        tables.put("Other",otherTable);
        assignPanel.add(otherTable);
        
        // TESTING ONLY - DELETE
        /*JTable testTab = tables.get("CS-UY 1134").getTable();
        DefaultTableModel model = (DefaultTableModel) testTab.getModel();
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});
        model.addRow(new Object[]{"1","2","3","4","5"});*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        scheduleButton = new javax.swing.JButton();
        assignmentButton = new javax.swing.JButton();
        fileButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        assignPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 196, 15));

        jPanel2.setBackground(new java.awt.Color(34, 116, 165));

        scheduleButton.setBackground(new java.awt.Color(34, 116, 165));
        scheduleButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        scheduleButton.setForeground(new java.awt.Color(255, 255, 255));
        scheduleButton.setText("Schedule");
        scheduleButton.setBorderPainted(false);
        scheduleButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        scheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleButtonActionPerformed(evt);
            }
        });

        assignmentButton.setBackground(new java.awt.Color(34, 116, 165));
        assignmentButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        assignmentButton.setForeground(new java.awt.Color(255, 255, 255));
        assignmentButton.setText("Assignments");
        assignmentButton.setBorderPainted(false);
        assignmentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        assignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentButtonActionPerformed(evt);
            }
        });

        fileButton.setBackground(new java.awt.Color(34, 116, 165));
        fileButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        fileButton.setForeground(new java.awt.Color(255, 255, 255));
        fileButton.setText("Files");
        fileButton.setBorderPainted(false);
        fileButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 196, 174));
        jLabel2.setText("SmartEDU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scheduleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignmentButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(46, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(25, 25, 25)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(scheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel2)
                    .addContainerGap(483, Short.MAX_VALUE)))
        );

        scrollPane.setPreferredSize(new java.awt.Dimension(970, 502));

        assignPanel.setBackground(new java.awt.Color(255, 255, 255));
        assignPanel.setMinimumSize(new java.awt.Dimension(968, 502));
        assignPanel.setPreferredSize(new java.awt.Dimension(968, 2002));

        javax.swing.GroupLayout assignPanelLayout = new javax.swing.GroupLayout(assignPanel);
        assignPanel.setLayout(assignPanelLayout);
        assignPanelLayout.setHorizontalGroup(
            assignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        assignPanelLayout.setVerticalGroup(
            assignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2002, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(assignPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleButtonActionPerformed
        this.setVisible(false);
        SmartEDUApp.main.setVisible(true);
    }//GEN-LAST:event_scheduleButtonActionPerformed

    private void assignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentButtonActionPerformed

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileButtonActionPerformed

    /*private void testOnly() {
        Random rand = new Random();
        int rVal = rand.nextInt(30,255);
        int gVal = rand.nextInt(30,255);
        int bVal = rand.nextInt(30,255);
        Color panelColor = new Color(rVal,gVal,bVal);
        JPanel newPanel = new JPanel();
        newPanel.setBackground(panelColor);
        newPanel.setSize(970,100);
        assignPanel.add(newPanel);
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignmentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignmentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignmentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignmentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignmentScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel assignPanel;
    private javax.swing.JButton assignmentButton;
    private javax.swing.JButton fileButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton scheduleButton;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
