/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.smarteduapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author ethan
 */
public class DeleteClassScreen extends javax.swing.JFrame {

    /**
     * Creates new form DeleteClassScreen
     */
    public DeleteClassScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        courseTitleField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Course");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 196, 15));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Delete Course");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course Title");

        confirmButton.setBackground(new java.awt.Color(34, 116, 165));
        confirmButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(34, 116, 165));
        cancelButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(courseTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(courseTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        this.setVisible(false);
        
        String courseToDelete = courseTitleField.getText();
        
        if (SmartEDUApp.main.gPanMon.courses.contains(courseToDelete)) {
            for (int i = 0; i < SmartEDUApp.main.gPanMon.blocks.size() ; i++) {
                CourseBlock curr = SmartEDUApp.main.gPanMon.blocks.get(i);
                if (curr.courseTitle.equals(courseToDelete)) {
                    SmartEDUApp.main.gPanMon.blocks.remove(i);
                }
            }
            SmartEDUApp.main.gPanMon.repaint();
        }
        if (SmartEDUApp.main.gPanTue.courses.contains(courseToDelete)) {
            for (int i = 0; i < SmartEDUApp.main.gPanTue.blocks.size() ; i++) {
                CourseBlock curr = SmartEDUApp.main.gPanTue.blocks.get(i);
                if (curr.courseTitle.equals(courseToDelete)) {
                    SmartEDUApp.main.gPanTue.blocks.remove(i);
                }
            }
            SmartEDUApp.main.gPanTue.repaint();
        }
        if (SmartEDUApp.main.gPanWed.courses.contains(courseToDelete)) {
            for (int i = 0; i < SmartEDUApp.main.gPanWed.blocks.size() ; i++) {
                CourseBlock curr = SmartEDUApp.main.gPanWed.blocks.get(i);
                if (curr.courseTitle.equals(courseToDelete)) {
                    SmartEDUApp.main.gPanWed.blocks.remove(i);
                }
            }
            SmartEDUApp.main.gPanWed.repaint();
        }
        if (SmartEDUApp.main.gPanThu.courses.contains(courseToDelete)) {
            for (int i = 0; i < SmartEDUApp.main.gPanThu.blocks.size() ; i++) {
                CourseBlock curr = SmartEDUApp.main.gPanThu.blocks.get(i);
                if (curr.courseTitle.equals(courseToDelete)) {
                    SmartEDUApp.main.gPanThu.blocks.remove(i);
                }
            }
            SmartEDUApp.main.gPanThu.repaint();
        }
        if (SmartEDUApp.main.gPanFri.courses.contains(courseToDelete)) {
            for (int i = 0; i < SmartEDUApp.main.gPanFri.blocks.size() ; i++) {
                CourseBlock curr = SmartEDUApp.main.gPanFri.blocks.get(i);
                if (curr.courseTitle.equals(courseToDelete)) {
                    SmartEDUApp.main.gPanFri.blocks.remove(i);
                }
            }
            SmartEDUApp.main.gPanFri.repaint();
        }
        if (SmartEDUApp.main.gPanSat.courses.contains(courseToDelete)) {
            for (int i = 0; i < SmartEDUApp.main.gPanSat.blocks.size() ; i++) {
                CourseBlock curr = SmartEDUApp.main.gPanSat.blocks.get(i);
                if (curr.courseTitle.equals(courseToDelete)) {
                    SmartEDUApp.main.gPanSat.blocks.remove(i);
                }
            }
            SmartEDUApp.main.gPanSat.repaint();
        }
        if (SmartEDUApp.main.gPanSun.courses.contains(courseToDelete)) {
            for (int i = 0; i < SmartEDUApp.main.gPanSun.blocks.size() ; i++) {
                CourseBlock curr = SmartEDUApp.main.gPanSun.blocks.get(i);
                if (curr.courseTitle.equals(courseToDelete)) {
                    SmartEDUApp.main.gPanSun.blocks.remove(i);
                }
            }
            SmartEDUApp.main.gPanSun.repaint();
        }
        
        // Delete from DB.
        Connection conn = null;
        Statement state = null;
        try {
            String url = "jdbc:mariadb://localhost:3307/academicdb";
            conn = DriverManager.getConnection(url,"root","");
            
            String deleteQuery = "delete from schedule where courseTitle = '"+courseToDelete+"'";
                    
            state = conn.createStatement();
            state.executeQuery(deleteQuery);
        } catch (Exception e) {
            
        } finally {
            if (state != null) try { state.close(); } catch (Exception e2) {}
            if (conn != null) try { conn.close(); } catch (Exception e3) {}
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteClassScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField courseTitleField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
